#undef ARCH_SIXTYFOUR
#define SIZEOF_INT 4
#define SIZEOF_LONG 4
#define SIZEOF_PTR 4
#define SIZEOF_SHORT 2
#define SIZEOF_LONGLONG 8
#define ARCH_INT64_TYPE long long
#define ARCH_UINT64_TYPE unsigned long long
#define ARCH_INT64_PRINTF_FORMAT "I64"
#define ARCH_SIZET_PRINTF_FORMAT "I"
#define INT64_LITERAL(s) s ## LL
#define FLAT_FLOAT_ARRAY
#undef ARCH_BIG_ENDIAN
#undef ARCH_ALIGN_DOUBLE
#undef ARCH_ALIGN_INT64
#undef NONSTANDARD_DIV_MOD
#undef ASM_CFI_SUPPORTED
#define PROFINFO_WIDTH 0
