#define OCAML_OS_TYPE "Win32"

#define HAS_STDINT_H
#undef BSD_SIGNALS
#define HAS_STRERROR
#define HAS_SOCKETS
#define HAS_GETCWD
#define HAS_UTIME
#define HAS_DUP2
#define HAS_GETHOSTNAME
#define HAS_MKTIME
#define HAS_PUTENV
#define HAS_LOCALE
#define HAS_BROKEN_PRINTF
#define HAS_IPV6
#define HAS_NICE
#define SUPPORT_DYNAMIC_LINKING
#define HAS_EXECVPE
