FROM ocamlcross/windows-x86-base:latest
MAINTAINER Romain Beauxis <toots@rastageeks.org>

ARG OPAM_PKG

USER opam

RUN opam list --short --recursive --external=mxe --required-by=$OPAM_PKG > /home/opam/mxe-deps

USER root

RUN cd /usr/src/mxe/ && cat /home/opam/mxe-deps | xargs make

USER opam

RUN eval $(opam config env) && opam install --verbose $OPAM_PKG

RUN opam list --short --recursive --external=mxe --depends-on=$OPAM_PKG > /home/opam/mxe-revdeps

USER root

RUN cd /usr/src/mxe/ && cat /home/opam/mxe-revdeps | xargs make

USER opam

RUN eval $(opam config env) && opam list --rec --short --sort --depends-on=$OPAM_PKG | while read i; do opam install --verbose "$i"; done
