FROM ocamlcross/windows-x64-base:latest
MAINTAINER Romain Beauxis <toots@rastageeks.org>

USER root

RUN rm -rf /home/opam/opam-cross-windows/packages

ADD packages/ /home/opam/opam-cross-windows/packages

RUN chown -R opam /home/opam/opam-cross-windows

USER opam

RUN opam pin --no-action add topkg https://github.com/whitequark/topkg.git

RUN opam update windows
