FROM dockcross/windows-x64
MAINTAINER Romain Beauxis <toots@rastageeks.org>

RUN apt-get update && apt-get install -y --force-yes gawk aspcud

WORKDIR /usr/src/mxe
RUN git pull origin master
RUN make cc

RUN useradd -g staff --create-home opam
USER opam

RUN curl -kL https://raw.github.com/hcarty/ocamlbrew/master/ocamlbrew-install | env CC=gcc OCAMLBREW_FLAGS="-r" bash

ENV PATH=/home/opam/ocamlbrew/ocaml-4.05.0/bin:$PATH

RUN opam init --auto --compiler=4.06.1

WORKDIR /home/opam/opam-cross-windows

ADD packages/ /home/opam/opam-cross-windows/packages

USER root

RUN chown -R opam /home/opam/opam-cross-windows

USER opam

RUN opam repository add windows /home/opam/opam-cross-windows

ENV TOOLPREF64=/usr/src/mxe/usr/bin/x86_64-w64-mingw32.static-

RUN eval $(opam config env) && opam install -y ocaml-windows
