FROM ocamlcross/windows-x64-pretest:4.06.1
MAINTAINER Romain Beauxis <toots@rastageeks.org>

ARG OPAM_PKG

RUN opam list --short --recursive --external=mxe --required-by=$OPAM_PKG > /home/opam/mxe-deps

USER root

RUN cd /usr/src/mxe/ && cat /home/opam/mxe-deps | xargs make

USER opam

RUN eval $(opam config env) && opam reinstall --verbose -y $OPAM_PKG
