ARG IMAGE
FROM $IMAGE
MAINTAINER Romain Beauxis <toots@rastageeks.org>

ARG COMPILER
ARG SYSTEM

RUN sed -i /etc/apt/sources.list -e 's#jessie#testing#g' && (apt-get update || true) && \
      apt-get install -y --force-yes gawk aspcud binutils automake lzip bubblewrap && \
      apt-get -y --force-yes autoremove && apt-get -y --force-yes clean

WORKDIR /usr/src/mxe
RUN git pull origin master && make cc

RUN wget https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh -O /tmp/install.sh && echo /usr/local/bin | sh /tmp/install.sh

RUN useradd -g staff --create-home opam

ADD packages/ /home/opam/opam-cross-arm/packages

ADD repo /home/opam/opam-cross-arm/repo

RUN chown -R opam /home/opam/opam-cross-arm

USER opam

WORKDIR /home/opam/opam-cross-arm

RUN opam init --auto --compiler=$COMPILER --disable-sandboxing

RUN opam repository add arm /home/opam/opam-cross-arm

RUN if [ "$SYSTEM" = "x64" ]; then \
      export TOOLPREF64=/usr/src/mxe/usr/bin/aarch64-linux-gnu- && \
      eval $(opam env) && opam update && \
      opam install -y ocaml-arm; \
    fi

RUN if [ "$SYSTEM" = "x86" ]; then \
      export TOOLPREF32=/usr/src/mxe/usr/bin/arm-linux-gnueabihf- && \
      eval $(opam env) && opam update && \
      opam install -y ocaml-arm; \
    fi
