FROM dockcross/windows-x64
MAINTAINER Romain Beauxis <toots@rastageeks.org>

RUN apt-get update && apt-get install -y --force-yes gawk aspcud bubblewrap

# For lame
RUN sed -i /etc/apt/sources.list -e 's#jessie#testing#g' && (apt-get update || true) && apt-get install -y --force-yes automake

WORKDIR /usr/src/mxe
RUN git pull origin master
RUN make cc

RUN wget https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh -O /tmp/install.sh && echo /usr/local/bin | sh /tmp/install.sh

RUN useradd -g staff --create-home opam

ADD packages/ /home/opam/opam-cross-windows/packages

ADD repo /home/opam/opam-cross-windows/repo

RUN chown -R opam /home/opam/opam-cross-windows

USER opam

WORKDIR /home/opam/opam-cross-windows

RUN opam init --auto --compiler=4.07.0 --disable-sandboxing

RUN opam repository add windows /home/opam/opam-cross-windows

ENV TOOLPREF64=/usr/src/mxe/usr/bin/x86_64-w64-mingw32.static-

RUN eval $(opam config env) && opam update && opam install -y ocaml-windows
